name: QA Deploy

on:
  push:
    branches:
      - develop
      - release/bb

jobs:
  generate_image_tag:
    name: Generate Docker Image Tag
    uses:  whiplashmerch/workflows/.github/workflows/generate_docker_image_tag.yml@main
    with:
      ecr_registry: ${{ vars.ECR_REGISTRY }}
      ecr_repo: ${{ vars.TRIVIAL_API_ECR_REPO }}
      env: "canary"

  build:
    name: "Build & Push Docker Image"
    uses: whiplashmerch/workflows/.github/workflows/build-rails-image-v2.yml@main
    needs: [generate_image_tag]
    with:
      ecr_registry: ${{ vars.ECR_REGISTRY }}
      ecr_repo: ${{ vars.TRIVIAL_API_ECR_REPO }}
      service_key: ${{ vars.TRIVIAL_API_SERVICE_KEY }}
      service_name: ${{ vars.TRIVIAL_API_SERVICE_NAME }}
      ecr_tags: ${{ needs.generate_image_tag.outputs.image_tag }}
    secrets:
      gh_pat: ${{ secrets.PROJECT_WORKFLOWS_TOKEN }}
      BUNDLE_GITHUB__COM: ${{ secrets.BUNDLE_GITHUB__COM }}
      BUNDLE_ENTERPRISE__CONTRIBSYS__COM: ${{ secrets.BUNDLE_ENTERPRISE__CONTRIBSYS__COM }}

  deploy:
    name: "Deploy to Canary-QA"
    needs: [generate_image_tag, build]
    uses: whiplashmerch/workflows/.github/workflows/run-terraform-v2.yml@main
    with:
      ecr_tag: ${{ needs.generate_image_tag.outputs.image_tag }}
      tf_target: "canary"
      repo_target: "terraform/service"
      tf_action: "apply"
      gh_environment_name: canary
    secrets: inherit