name: Production/Sandbox Deploy

on:
  push:
    branches:
      - main
      - release/bb

jobs:
  generate_image_tag:
    name: Generate Docker Image Tag
    uses: whiplashmerch/workflows/.github/workflows/generate_docker_image_tag.yml@main
    with:
      ecr_registry: ${{ vars.ECR_REGISTRY }}
      ecr_repo: ${{ vars.TRIVIAL_API_ECR_REPO }}
      env: "production"

  build:
    name: "Build & Push Docker Image"
    needs: [generate_image_tag]
    uses: whiplashmerch/workflows/.github/workflows/build-rails-image-v3.yml@main
    with:
      ecr_registry: ${{ vars.ECR_REGISTRY }}
      ecr_repo: ${{ vars.TRIVIAL_API_ECR_REPO }}
      service_key: ${{ vars.TRIVIAL_API_SERVICE_KEY }}
      service_name: ${{ vars.TRIVIAL_API_SERVICE_NAME }}
      ecr_tags: ${{ needs.generate_image_tag.outputs.image_tag }}
    secrets:
      org_app_id: ${{ secrets.ORG_GITHUB_APP_ID }}
      org_app_key: ${{ secrets.ORG_GITHUB_APP_PRIVATE_KEY }}
      BUNDLE_GITHUB__COM: ${{ secrets.BUNDLE_GITHUB__COM }}
      BUNDLE_ENTERPRISE__CONTRIBSYS__COM: ${{ secrets.BUNDLE_ENTERPRISE__CONTRIBSYS__COM }}

  deploy_sandbox:
    name: "Deploy to Sandbox"
    needs: [generate_image_tag, build]
    uses: whiplashmerch/workflows/.github/workflows/run-terraform-v3.yml@main
    with:
      ecr_tag: ${{ needs.generate_image_tag.outputs.image_tag }}
      tf_target: "sandbox"
      repo_target: "terraform/service"
      tf_action: "apply"
      gh_environment_name: sandbox
    secrets:
      org_app_id: ${{ secrets.ORG_GITHUB_APP_ID }}
      org_app_key: ${{ secrets.ORG_GITHUB_APP_PRIVATE_KEY }}
      dd_api_key: ${{ secrets.DATADOG_API_KEY }}

  deploy_production:
    name: "Deploy to Production"
    needs: [generate_image_tag, build, deploy_sandbox]
    uses: whiplashmerch/workflows/.github/workflows/run-terraform-v3.yml@main
    with:
      ecr_tag: ${{ needs.generate_image_tag.outputs.image_tag }}
      tf_target: "production"
      repo_target: "terraform/service"
      tf_action: "apply"
      gh_environment_name: production
    secrets:
      org_app_id: ${{ secrets.ORG_GITHUB_APP_ID }}
      org_app_key: ${{ secrets.ORG_GITHUB_APP_PRIVATE_KEY }}
      dd_api_key: ${{ secrets.DATADOG_API_KEY }}

  tag:
    needs: [generate_image_tag, deploy_production]
    name: "Add RC Git Tags"
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Generate org token
        id: org_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.ORG_GITHUB_APP_ID }}
          private-key: ${{ secrets.ORG_GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ needs.generate_image_tag.outputs.git_tag }}
          tag_exists_error: false
          github_token: ${{ steps.org_token.outputs.token }}


  notify:
    needs: [ generate_image_tag, deploy_production ]
    name: Notify Slack
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "service_name": "${{ vars.TRIVIAL_API_SERVICE_NAME }}",
              "release": "${{ needs.generate_image_tag.outputs.git_tag }}",
              "env": "sandbox & production"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_AUTOMATIONS_WEBHOOK }}