name: QA Deploy

on:
  push:
    branches:
      - $default-branch
      - bb/adds_tf


jobs:
  generate_image_tag:
    uses: whiplashmerch/workflows/.github/workflows/generate-docker-image-tag/action.yml@bb/updates_rails_image_build
    with:
      enviroment: canary

  build:
    name: "Build & Push Docker Image"
    uses: whiplashmerch/workflows/.github/workflows/build-rails-image.yml@bb/updates_rails_image_build
    with:
      ecr_registry: ${{ vars.ECR_REGISTRY }}
      ecr_repo: ${{ vars.ECR_REPO }}
      service_key: "tapi"
      service_name: "Trivial API"
      override_image_tags:
    secrets:
      gh_pat: ${{ secrets.PROJECT_WORKFLOWS_TOKEN }}
      BUNDLE_GITHUB__COM: ${{ secrets.BUNDLE_GITHUB__COM }}
      BUNDLE_ENTERPRISE__CONTRIBSYS__COM: ${{ secrets.BUNDLE_ENTERPRISE__CONTRIBSYS__COM }}


  deploy:
    name: "Deploy to Staging"
    needs: [classify, build]
    uses: whiplashmerch/workflows/.github/workflows/run-terraform-v2.yml@fe-vue-prod
    with:
      ecr_tag: ${{ needs.classify.outputs.human_tag }}
      tf_target: "stable"
      repo_target: "infra/terraform"
      tf_action: "apply"
      gh_environment_name: canary
    secrets: inherit